#                                                                       
#      *****                                                            
#   ******                  *                                           
#  **   *  *    **         ***                                          
# *    *  *   **** *        *                                           
#     *  *     ****                                             ****    
#    ** **    * **        ***     ***  ****        ****        * **** * 
#    ** **   *             ***     **** **** *    *  ***  *   **  ****  
#    ** *****               **      **   ****    *    ****   ****       
#    ** ** ***              **      **    **    **     **      ***      
#    ** **   ***            **      **    **    **     **        ***    
#    *  **    ***           **      **    **    **     **          ***  
#       *       ***         **      **    **    **     **     ****  **  
#   ****         ***        **      **    **    **     **    * **** *   
#  *  *****        ***  *   *** *   ***   ***    ********       ****    
# *    ***           ***     ***     ***   ***     *** ***              
# *                                                     ***             
#  **                                             ****   ***            
#                                               *******  **             
#                                              *     ****               
#                                                                       

background-opacity = 0.88

# Background and foreground colors
background = #261e12
foreground = #d9c27a

# Standard colors
palette = 0=#261e12
palette = 1=#a33d4e
palette = 2=#2f7f88
palette = 3=#c8a03c
palette = 4=#7550a3
palette = 5=#2e6fb8
palette = 6=#5d7d3a
palette = 7=#d9c27a

# Bright colors
palette = 8=#564a38
palette = 9=#cf6f7e
palette = 10=#56b8a6
palette = 11=#efcf72
palette = 12=#a37dcb
palette = 13=#79abd6
palette = 14=#8eb866
palette = 15=#f3e6bf

#               .;                          
#    .;;.    .-.;'     .'                   
#   ;;  `;`-' .;  .-..'                     
#  ;;    :.  ::  :   ;                      
# ;;     ;'_;;_.-`:::'`.                    
# `;.__.'  .;;;        .           .        
#           .;'      .'          .'         
#          .;'.-.   ;-.   .-.   ;-.   .-.   
# .-.     .;';   ;';   ; ;   ;';   ; ;   ;' 
# `.     .;  `;;'.'`::'`-`;;'.'`::'`-`;;'   
#   `;;;;;;'                                
