-- Generated by scripts/hypr2lua.
-- Source: omarchy-kings-theme/hyprland.conf

local activeBorderColor = {
  colors = { "rgba(564a38ee)", "rgba(c8a03cee)", "rgba(564a38ee)" },
  angle = 45,
}
local inactiveBorderColor = "rgba(564a3855)"
local activeShadowColor = "rgba(00000099)"
local inactiveShadowColor = "rgba(0000004d)"

hl.config({
  general = {
    col = {
      active_border = activeBorderColor,
      inactive_border = inactiveBorderColor,
    },
    border_size = 2,
    gaps_in = 5,
    gaps_out = 10,
  },
  group = {
    col = {
      border_active = activeBorderColor,
      border_inactive = inactiveBorderColor,
    },
  },
  decoration = {
    rounding = 0,
    dim_inactive = true,
    dim_strength = 0.15,
    active_opacity = 1.0,
    inactive_opacity = 0.95,
    blur = {
      enabled = true,
      size = 5,
      passes = 3,
      noise = 0.08,
      contrast = 1.18,
      brightness = 0.86,
      vibrancy = 0.22,
      vibrancy_darkness = 0.83,
      ignore_opacity = true,
      new_optimizations = true,
      xray = false,
      special = false,
      popups = true,
      popups_ignorealpha = 0.65,
    },
    shadow = {
      enabled = true,
      range = 20,
      render_power = 3,
      offset = "2 4",
      color = activeShadowColor,
      color_inactive = inactiveShadowColor,
    },
  },
})

hl.curve("regnalEase", { type = "bezier", points = { { 0.4, 0 }, { 0.2, 1 } } })

hl.animation({
  leaf = "borderangle",
  enabled = true,
  speed = 20,
  bezier = "regnalEase",
  style = "once",
})
hl.animation({
  leaf = "windows",
  enabled = true,
  speed = 4,
  bezier = "regnalEase",
  style = "slide",
})
hl.animation({
  leaf = "windowsIn",
  enabled = true,
  speed = 4,
  bezier = "regnalEase",
  style = "slide",
})
hl.animation({
  leaf = "windowsOut",
  enabled = true,
  speed = 3,
  bezier = "regnalEase",
  style = "slide",
})
hl.animation({
  leaf = "fade",
  enabled = true,
  speed = 4,
  bezier = "regnalEase",
})
hl.animation({
  leaf = "workspaces",
  enabled = true,
  speed = 5,
  bezier = "regnalEase",
  style = "slide",
})
